-- Standalone descending index on AuditLog.timestamp.
--
-- Two queries scan this table with no userId predicate, and neither can use the
-- existing "AuditLog_userId_timestamp_idx" because that index needs a leading
-- userId to be usable:
--
--   * /api/admin/export  — ORDER BY timestamp DESC, id ASC over a date range
--   * retention purge    — WHERE timestamp < cutoff, up to 200 statements a run
--
-- Both were therefore a sequential scan plus an external sort of the whole
-- table on every invocation.
--
-- CONCURRENTLY is deliberately not used: Prisma Migrate wraps each migration in
-- a transaction, and CREATE INDEX CONCURRENTLY cannot run inside one. On a
-- large AuditLog this takes a brief ACCESS SHARE lock; run it during a quiet
-- window, or create the index by hand with CONCURRENTLY and mark the migration
-- applied.
CREATE INDEX "AuditLog_timestamp_idx" ON "AuditLog"("timestamp" DESC);
