apiVersion: v1
kind: Service
metadata:
  name: {{ include "secureflow.fullname" . }}-app
  labels:
    {{- include "secureflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "secureflow.selectorLabels" . | nindent 4 }}
